<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE capabalityprofile [

<!ELEMENT capabilityprofile (profile*)>
<!ATTLIST capabilityprofile
          id ID #REQUIRED
          title CDATA #REQUIRED>


<!ELEMENT profile (serviceprofile|profile)*>


<!ELEMENT serviceprofile (description*, reftaxonomy+, obgroup+, guide*)>
<!ATTLIST serviceprofile
          title CDATA #REQUIRED>

<!ELEMENT description (#PCDATA)>

<!ELEMENT reftaxonomy EMPTY>
<!ATTLIST reftaxonomy
          refid IDREF #REQUIRED>

<!ELEMENT obgroup (refstandard*)>
<!ATTLIST obgroup
          obligation (mandatory|required|optional|conditional) #REQUIRED>

<!ELEMENT refstandard EMPTY>
<!ATTLIST refstandard
          refid IDREF #REQUIRED>

<!ELEMENT guide (#PCDATA)>

]>


<capabilityprofile id="fmn1" title="FMN Spiral 1 Profile">
   <profile id="fmn-fed-com-net" title="Federated Communication and Networking Profile">
      <profile id="fmn-fed-com" title="Federated Communication Profile">
         <serviceprofile title="Inter-Autonomous Systems IP Transport Profile">
            <description>The Inter-Autonomous Systems IP Transport Profile provides standards and guidance for Edge Transport Services between autonomous systems, using Internet Protocol (IP) over point-to-point Ethernet links on optical fibre.</description>
            <reftaxonomy refid="ts-cs-tn-edge-iptrans"/>
            <obgroup obligation="mandatory">
               <refstandard refid="ietf-rfc826"/>
            </obgroup>
            <obgroup obligation="mandatory">
               <refstandard refid="iso-iec-11801"/>
               <refstandard refid="itu-t-g.652"/>
               <refstandard refid="iec-61754-20"/>
            </obgroup>
            <obgroup obligation="mandatory">
               <refstandard refid="ieee-802.3-2013"/>
            </obgroup>
         </serviceprofile>
         <serviceprofile title="IP Routing Information Profile">
            <description>The IP Routing Information Profile provides standards and guidance for support of the Routing Information Protocol (RIP) to expand the amount of useful information carried in RIP messages and to add a measure of security.</description>
            <reftaxonomy refid="ts-cs-tn-edge-iptrans"/>
            <obgroup obligation="optional">
               <refstandard refid="ietf-rfc2453"/>
            </obgroup>
         </serviceprofile>
         <serviceprofile title="Inter-Autonomous Systems Multicast Routing Profile">
            <description>The Inter-Autonomous Systems Multicast Routing Profile provides standards and guidance for multicast routing between inter-autonomous systems.</description>
            <reftaxonomy refid="ts-cs-tn-edge-iptrans"/>
            <reftaxonomy refid="ts-cs-ca-pba-ipv4"/>
            <obgroup obligation="mandatory">
               <refstandard refid="ietf-rfc3618"/>
               <refstandard refid="ietf-rfc4760"/>
            </obgroup>
            <obgroup obligation="mandatory">
               <refstandard refid="ietf-rfc4601"/>
               <refstandard refid="ietf-rfc1112"/>
               <refstandard refid="ietf-rfc3376"/>
            </obgroup>
            <obgroup obligation="mandatory">
               <refstandard refid="ietf-rfc2908"/>
               <refstandard refid="ietf-rfc3171"/>
               <refstandard refid="ietf-rfc2365"/>
            </obgroup>
         </serviceprofile>
         <serviceprofile title="IP Quality of Service Profile">
            <description>The IP Quality of Service Profile provides standards and guidance to establish and control an agreed level of performance for IP services in federated networks.</description>
            <reftaxonomy refid="ts-cs-tn-core-packetroute"/>
            <reftaxonomy refid="ts-cs-ca-pba-ipv4"/>
            <obgroup obligation="mandatory">
               <refstandard refid="ietf-rfc2474"/>
               <refstandard refid="ietf-rfc4594"/>
               <refstandard refid="itu-t-y.1540"/>
               <refstandard refid="itu-t-y.1541"/>
               <refstandard refid="itu-t-y.1542"/>
               <refstandard refid="itu-t-m.2301"/>
               <refstandard refid="itu-t-j.241"/>
            </obgroup>
            <obgroup obligation="mandatory">
               <refstandard refid="nato-stanag4711"/>
            </obgroup>
         </serviceprofile>
         <serviceprofile title="Inter-Autonomous Systems Routing Profile">
            <description>The Inter-Autonomous Systems Routing Profile provides standards and guidance for routing between inter-autonomous systems</description>
            <reftaxonomy refid="ts-cs-tn-core-packetroute"/>
            <reftaxonomy refid="ts-cs-ca-pba-ipv4"/>
            <obgroup obligation="required">
               <refstandard refid="ietf-rfc5668"/>
            </obgroup>
            <obgroup obligation="mandatory">
               <refstandard refid="ietf-rfc4632"/>
            </obgroup>
            <obgroup obligation="mandatory">
               <refstandard refid="ietf-rfc1997"/>
               <refstandard refid="ietf-rfc4360"/>
               <refstandard refid="ietf-rfc3392"/>
               <refstandard refid="ietf-rfc4271"/>
               <refstandard refid="ietf-rfc4760"/>
            </obgroup>
         </serviceprofile>
         <serviceprofile title="Inter-Autonomous Systems TDM Transport Profile">
            <description>The Inter-Autonomous Systems TDM Transport
            Profile provides standards and guidance for Edge Transport
            Services between autonomous systems, using Time Division
            Multiplex (TDM) over a Wide Area Network
            (WAN).</description>
            <reftaxonomy refid="ts-cs-tn-edge-timediv"/>
            <obgroup obligation="mandatory">
               <refstandard refid="itu-t-g.703"/>
               <refstandard refid="itu-t-g.704"/>
            </obgroup>
            <obgroup obligation="mandatory">
               <refstandard refid="ietf-rfc3544"/>
               <refstandard refid="ietf-rfc1994"/>
               <refstandard refid="ietf-rfc1661"/>
            </obgroup>
            <guide>This interconnection is based on STANAG 5067,
Standard for interconnection of IPv4 networks at
Mission Secret and unclassified security Levels.
STANAG 5067 provides additional
implementation, security and management
guidance.</guide>
            <guide>Combined with TRANSEC crypto or other forms
of link protection, CHAP (IETF RFC 1994) is not
required. Otherwise, CHAP is recommended.</guide>
         </serviceprofile>
         <serviceprofile title="Routing Encapsulation Profile">
           <description>The Routing Encapsulation Profile provides
           standards and guidance for generic routing encapsulation
           functions between network interconnection points
           (NIPs)</description>
            <reftaxonomy refid="ts-cs-tn-edge-iptrans"/>
            <obgroup obligation="mandatory">
               <refstandard refid="ietf-rfc2890"/>
               <refstandard refid="ietf-rfc2409"/>
               <refstandard refid="ietf-rfc4303"/>
            </obgroup>
         </serviceprofile>
      </profile>
      <profile id="fmn-fed-net" title="Federated Networking Profile">
         <serviceprofile title="Directory Data Structure Profile">
            <description>The Directory Data Structure Profile provides standards and guidance in support of the definition of the namespace of a federated mission network on the basis of the Lightweight Directory Access Protocol (LDAP)</description>
            <reftaxonomy refid="ts-ces-is-ss-directory"/>
            <obgroup obligation="mandatory">
               <refstandard refid="ietf-rfc2798"/>
               <refstandard refid="ietf-rfc4519"/>
            </obgroup>
         </serviceprofile>
         <serviceprofile title="Digital Certificate Profile">
            <description>The Digital Certificate Profile provides standards and guidance in support of a Public Key Infrastructure (PKI) on federated mission networks.</description>
            <obgroup obligation="mandatory">
               <refstandard refid="itu-t-x.509"/>
               <refstandard refid="ietf-rfc5280"/>
               <refstandard refid="ietf-rfc6960"/>
            </obgroup>
            <guide>The version of the encoded public key certificate shall be version 3. The version of the encoded certificate revocation list (CRL) shall be version 2.</guide>
            <guide>Additional Implementation Guidance:
            <itemizedlist>
                  <listitem>
                     <para>AC/322-D(2004)0024-REV2-ADD2 - "NATO
Public Key Infrastructure (NPKI) Certificate
Policy"</para>
                  </listitem>
                  <listitem>
                     <para>AC/322-D(2010)0036 - "NATO Cryptographic
  Interoperability Strategy"</para>
                  </listitem>
               </itemizedlist>
            </guide>
         </serviceprofile>
         <serviceprofile title="Directory Data Exchange Profile">
            <description>The Directory Data Exchange Profile provides standards and guidance in support of a mechanism used to connect to, search, and modify Internet directories on the basis of the Lightweight Directory Access Protocol (LDAP).</description>
            <reftaxonomy refid="ts-ces-is-ss-directory"/>
            <obgroup obligation="mandatory">
               <refstandard refid="ietf-rfc4510"/>
               <refstandard refid="ietf-rfc4511"/>
               <refstandard refid="ietf-rfc4512"/>
               <refstandard refid="ietf-rfc4513"/>
               <refstandard refid="ietf-rfc4514"/>
               <refstandard refid="ietf-rfc4515"/>
               <refstandard refid="ietf-rfc4516"/>
               <refstandard refid="ietf-rfc4517"/>
               <refstandard refid="ietf-rfc4518"/>
               <refstandard refid="ietf-rfc4519"/>
               <refstandard refid="ietf-rfc2849"/>
            </obgroup>
         </serviceprofile>
         <serviceprofile title="Network Authentication Profile">
            <description>The Network Authentication Profile provides standards and guidance for to provide strong authentication for client/server applications by using secret-key cryptography on the basis of the Kerberos authentication protocol</description>
            <obgroup obligation="mandatory">
               <refstandard refid="ietf-rfc4121"/>
               <refstandard refid="ietf-rfc4422"/>
               <refstandard refid="ietf-rfc4505"/>
               <refstandard refid="ietf-rfc4616"/>
               <refstandard refid="ietf-rfc4752"/>
            </obgroup>
            <obgroup obligation="mandatory">
               <refstandard refid="ietf-rfc4120"/>
            </obgroup>
         </serviceprofile>
         <serviceprofile title="Time Synchronization Profile">
            <description>The Time Synchronization Profile provides standards and guidance to support the synchronization of clocks across a network or a federation of networks and the safeguard of the accurate use of time stamps.</description>
            <reftaxonomy refid="ts-ces-is-net-disttime"/>
            <obgroup obligation="mandatory">
               <refstandard refid="ietf-rfc5905"/>
               <refstandard refid="itu-r-tf.460-6"/>
            </obgroup>
            <guide>A stratum-1 time server is directly linked (not
over a network path) to a reliable source of UTC
time (Universal Time Coordinate) such as GPS,
WWV, or CDMA transmissions through a modem
connection, satellite, or radio.</guide>
            <guide>Stratum-1 devices must implement IPv4 so that
they can be used as timeservers for IPv4 Mission
      Network Elements.</guide>
         </serviceprofile>
         <serviceprofile title="Domain Naming Profile">
            <description>The Domain Naming Profile provides standards and guidance to support the hierarchical distributed naming system for computers, services, or any resource connected to a federated mission network.</description>
            <reftaxonomy refid="ts-ces-is-net-dns"/>
            <obgroup obligation="mandatory">
               <refstandard refid="ietf-rfc1034"/>
               <refstandard refid="ietf-rfc1035"/>
               <refstandard refid="ietf-rfc1032"/>
               <refstandard refid="ietf-rfc2181"/>
               <refstandard refid="ietf-rfc2782"/>
            </obgroup>
         </serviceprofile>
      </profile>
   </profile>
   <profile id="fmn-fed-hum-comm" title="Federated Human-to-Human Communications Profile">
      <profile id="fmn-uni-collab" title="Federated Unified Collaboration Profile">
         <serviceprofile title="Content Encapsulation Profile">
            <description>The Content Encapsulation Profile provides standards and guidance for content encapsulation within bodies of interne messages, following the Multipurpose Internet Mail Extensions (MIME) specification.</description>
            <reftaxonomy refid="ts-ces-es-cc-im"/>
            <obgroup obligation="mandatory">
               <refstandard refid="ietf-rfc2045"/>
               <refstandard refid="ietf-rfc2046"/>
               <refstandard refid="ietf-rfc2047"/>
               <refstandard refid="ietf-rfc2049"/>
               <refstandard refid="ietf-rfc4288"/>
            </obgroup>
            <guide>10 MB max message size limit</guide>
            <guide>Minimum Content-Transfer-Encoding:
        <itemizedlist>
                  <listitem>
                     <para>7bit</para>
                  </listitem>
                  <listitem>
                     <para>base64</para>
                  </listitem>
                  <listitem>
                     <para>binary BINARYMIME SMTP extension (RFC 3030)</para>
                  </listitem>
               </itemizedlist>
            </guide>
            <guide>Minimum set of media and content-types:
        <itemizedlist>
                  <listitem>
                     <para>text/plain (RFC 1521)</para>
                  </listitem>
                  <listitem>
                     <para>text/enriched (RFC 1896)</para>
                  </listitem>
                  <listitem>
                     <para>text/html (RFC 1866)</para>
                  </listitem>
                  <listitem>
                     <para>multipart/mixed (RFC 2046)</para>
                  </listitem>
                  <listitem>
                     <para>multipart/signed</para>
                  </listitem>
               </itemizedlist>
            </guide>
         </serviceprofile>
         <serviceprofile title="Informal Messaging Profile">
            <description>The Informal Messaging Profile provides standards and guidance for SMTP settings and the marking and classification of informal messages.</description>
            <reftaxonomy refid="ts-ces-es-cc-im"/>
            <obgroup obligation="mandatory">
               <refstandard refid="ietf-rfc5321"/>
               <refstandard refid="ietf-rfc1870"/>
               <refstandard refid="ietf-rfc1985"/>
               <refstandard refid="ietf-rfc2034"/>
               <refstandard refid="ietf-rfc2920"/>
               <refstandard refid="ietf-rfc3207"/>
               <refstandard refid="ietf-rfc3461"/>
               <refstandard refid="ietf-rfc3798"/>
               <refstandard refid="ietf-rfc3885"/>
               <refstandard refid="ietf-rfc4954"/>
            </obgroup>
            <guide>Depending on the protection requirements within the particular FMN instance messages must be marked in the message header field "Keywords"(IETF RFC 2822) and firstline-of-text in the message body according to the following convention: [MMM] [CLASSIFICATION], Releasable to [MISSION] Where CLASSIFICATION is the classification {SECRET, CONFIDENTIAL, RESTRICTED} or UNCLASSIFIED, and MMM is the ISO 3166-1 alpha-3 country code with the exception that NATO will be identified by the four letter acronym "NATO". The "releasable to" list shall include the short-name of the mission and may be extended to include other entities.</guide>
            <guide>Example: Keywords: ITA UNCLASSIFIED,
Releasable to XFOR Conditional (if the mission
network operates at classified level).</guide>
         </serviceprofile>
         <serviceprofile title="Numbering Plans Profile">
            <description>The Numbering Plans Profile provides standards and guidance for the facilitation of numbering plans of                                         telecommunications, audio and video networks.</description>
            <reftaxonomy refid="ts-ces-es-cc-ac"/>
            <reftaxonomy refid="ts-ces-es-cc-vc"/>
            <obgroup obligation="mandatory">
               <refstandard refid="nato-stanag4705"/>
               <refstandard refid="nato-stanag5046"/>
               <refstandard refid="itu-t-e.164"/>
            </obgroup>
         </serviceprofile>
         <serviceprofile title="Audio-based Collaboration Profile">
            <description>The Audio-based Collaboration Profile provides standards and guidance for the implementation of an interoperable voice system (telephony) on federated mission networks.</description>
            <reftaxonomy refid="ts-ces-es-cc-ac"/>
            <obgroup obligation="mandatory">
               <refstandard refid="ietf-rfc3261"/>
               <refstandard refid="ietf-rfc3262"/>
               <refstandard refid="ietf-rfc3264"/>
               <refstandard refid="ietf-rfc3311"/>
               <refstandard refid="ietf-rfc3428"/>
               <refstandard refid="ietf-rfc4028"/>
               <refstandard refid="ietf-rfc4412"/>
               <refstandard refid="ietf-rfc4566"/>
            </obgroup>
            <obgroup obligation="mandatory">
               <refstandard refid="ietf-rfc3550"/>
            </obgroup>
            <obgroup obligation="mandatory">
               <refstandard refid="itu-t-g.729"/>
            </obgroup>
            <guide>Voice over IP (VoIP) refers to unprotected voice
communication services running on unclassified
IP networks e.g. conventional IP telephony.
Voice over Secure IP (VoSIP) refers to
non-protected voice service running on a
classified IP networks. Depending on the security
classification of a FMN instance, VoIP or VoSIP
is mandatory. If a member choses to use
network agnostic Secure Voice services in
addition to VoSIP, then SCIP specifications as
defined for audio-based collaboration services
(end-to-end protected voice) should be used.</guide>
            <guide>The voice sampling interval is 40ms.</guide>
         </serviceprofile>
         <serviceprofile title="Secure Voice Profile">
            <description>The Secure Voice Profile provides standards and guidance for the facilitation of secure telephony and other protected                                      audio-based collaboration on federated mission networks.</description>
            <reftaxonomy refid="ts-ces-es-cc-ac"/>
            <obgroup obligation="conditional">
               <refstandard refid="itu-t-v.150.1"/>
               <refstandard refid="iicwg-scip-210"/>
               <refstandard refid="iicwg-scip-214"/>
               <refstandard refid="iicwg-scip-215"/>
               <refstandard refid="iicwg-scip-216"/>
               <refstandard refid="iicwg-scip-220"/>
               <refstandard refid="iicwg-scip-221"/>
               <refstandard refid="iicwg-scip-233"/>
            </obgroup>
         </serviceprofile>
         <serviceprofile title="Basic Text-based Collaboration Profile">
            <description>The Basic Text-based Collaboration Profile provides standards and guidance to establish a basic near-real time text-based group collaboration capability (chat) for time critical reporting and decision making in military operations.</description>
            <reftaxonomy refid="ts-ces-es-cc-tc"/>
            <reftaxonomy refid="ts-ces-es-cc-presence"/>
            <obgroup obligation="optional">
               <refstandard refid="xmpp-xep-0288"/>
            </obgroup>
            <obgroup obligation="mandatory">
               <refstandard refid="xmpp-xep-0004"/>
               <refstandard refid="xmpp-xep-0030"/>
               <refstandard refid="xmpp-xep-0045"/>
               <refstandard refid="xmpp-xep-0049"/>
               <refstandard refid="xmpp-xep-0050"/>
               <refstandard refid="xmpp-xep-0054"/>
               <refstandard refid="xmpp-xep-0092"/>
               <refstandard refid="xmpp-xep-0096"/>
               <refstandard refid="xmpp-xep-0114"/>
               <refstandard refid="xmpp-xep-0115"/>
               <refstandard refid="xmpp-xep-0203"/>
               <refstandard refid="xmpp-xep-0220"/>
            </obgroup>
            <obgroup obligation="mandatory">
               <refstandard refid="ietf-rfc6120"/>
               <refstandard refid="ietf-rfc6121"/>
            </obgroup>
         </serviceprofile>
         <serviceprofile title="Video-based Collaboration Profile">
            <description>The Video-based Collaboration Profile provides standards and guidance for the implementation and configuration of Video Tele Conferencing (VTC) systems and services in a federated mission network.</description>
            <reftaxonomy refid="ts-ces-es-cc-vc"/>
            <obgroup obligation="conditional">
               <refstandard refid="ietf-rfc4582"/>
               <refstandard refid="itu-t-h.239"/>
            </obgroup>
            <obgroup obligation="mandatory">
               <description/>
               <refstandard refid="itu-t-g.722"/>
            </obgroup>
            <obgroup obligation="mandatory">
               <refstandard refid="itu-t-h.323"/>
               <refstandard refid="itu-t-h.225"/>
               <refstandard refid="itu-t-h.245"/>
               <refstandard refid="itu-t-h.264"/>
               <refstandard refid="itu-t-h.263"/>
               <refstandard refid="itu-t-6.722"/>
               <refstandard refid="ietf-rfc3550"/>
            </obgroup>
            <guide>It Is recommended that dynamic port ranges are
constrained to a limited and agreed number. This
is an activity that needs to be performed at the
mission planning stage. Different vendors have
different limitations on fixed ports. However
common ground can always be found.</guide>
            <guide>As a Minimum G.722.1 is to be used. Others are
exceptions and need to be agreed by the MN
administrative authority for video calls.</guide>
         </serviceprofile>
      </profile>
      <profile id="fmn-fed-inf-mgnt" title="Federated Information Management Profile">
         <serviceprofile title="File Format Profile">
            <description>The File Format Profile provides standards and guidance for the collaborative generation of spreadsheets, charts, presentations and word processing documents.</description>
            <reftaxonomy refid="ts-ces-soa-web-host"/>
            <reftaxonomy refid="ts-ces-es-cc-im"/>
            <obgroup obligation="mandatory">
               <refstandard refid="iso-iec-10918-1"/>
               <refstandard refid="iso-iec-10918-3"/>
            </obgroup>
            <obgroup obligation="required">
               <refstandard refid="iso-iec-26300"/>
            </obgroup>
            <obgroup obligation="mandatory">
               <refstandard refid="iso-iec-29500"/>
            </obgroup>
            <obgroup obligation="mandatory">
               <description/>
               <refstandard refid="iso-19005-1"/>
               <refstandard refid="iso-19005-2"/>
               <refstandard refid="iso-32000-1"/>
            </obgroup>
            <guide>ISO/IEC 29500 and ISO/IEC 26300 are both
open document formats for XML-based saving
and exchanging word processing documents,
spreadsheets and presentations. They differ in
design and scope.</guide>
         </serviceprofile>
         <serviceprofile title="Internationalization Profile">
            <description>The Internationalization Profile provides standards and guidance for the design and development of content and (web) applications, in a way that ensures it will work well for, or can be easily adapted for, users from any culture, region, or language.</description>
            <reftaxonomy refid="ts-ces-soa-web-host"/>
            <obgroup obligation="required">
               <refstandard refid="w3c-rec-charmod-20050215"/>
               <refstandard refid="w3c-rec-its-20070403"/>
               <refstandard refid="w3c-rec-its20-20131029"/>
               <refstandard refid="w3c-rec-ruby-20010531"/>
            </obgroup>
            <guide>Best practices and tutorials on
internationalization can be found at:
http://www.w3.org/International/articlelist.</guide>
         </serviceprofile>
         <serviceprofile title="Character Encoding Profile">
            <description>The Character Encoding Profile provides standards and guidance for the encoding of character sets.</description>
            <reftaxonomy refid="ts-ces-soa-web-host"/>
            <obgroup obligation="mandatory">
               <description/>
               <refstandard refid="ietf-rfc3629"/>
            </obgroup>
         </serviceprofile>
      </profile>
      <profile id="fmn-fed-web-host" title="Federated Web Hosting Profile">
         <serviceprofile title="Web Platform Profile">
            <description>The Web Platform Profile provides standards and guidance to enable web technology on federated mission networks.</description>
            <reftaxonomy refid="ts-ces-soa-web-host"/>
            <obgroup obligation="mandatory">
               <refstandard refid="ietf-rfc2616"/>
               <refstandard refid="ietf-rfc2817"/>
               <refstandard refid="ietf-rfc3986"/>
               <refstandard refid="ietf-rfc1738"/>
            </obgroup>
            <guide>HTTP shall be used as the transport protocol for
information without 'need-to-know' caveats
between all service providers and consumers
(unsecured HTTP traffic). HTTPS shall be used
as the transport protocol between all service
providers and consumers to ensure
confidentiality requirements (secured HTTP
traffic). Unsecured and secured HTTP traffic
shall share the same port.</guide>
         </serviceprofile>
         <serviceprofile title="Web Content Profile">
            <description>The Web Content Profile provides standards and guidance for the processing, sharing and presentation of web content on federated mission networks. Web presentation services must be based on a fundamental set of basic and widely understood protocols, such as those listed below. Proprietary or compiled components shall be avoided (e.g. Microsoft Web Parts, Microsoft Silverlight or Adobe Flash).</description>
            <reftaxonomy refid="ts-ces-soa-web-host"/>
            <obgroup obligation="mandatory">
               <refstandard refid="iso-iec-15445"/>
               <refstandard refid="ietf-rfc2854"/>
               <refstandard refid="ietf-rfc4329"/>
               <refstandard refid="w3c-rec-html5-20141028"/>
               <refstandard refid="w3c-rec-css3-mediaqueries-20120619"/>
               <refstandard refid="w3c-rec-css3-selectors-20110929"/>
               <refstandard refid="ietf-rfc2616"/>
               <refstandard refid="ietf-rfc2817"/>
            </obgroup>
            <obgroup obligation="mandatory">
               <refstandard refid="w3c-rec-css2-2011067"/>
               <refstandard refid="w3c-cr-css-style-attr-20101012"/>
               <refstandard refid="w3c-rec-css-namespaces-3-20140320"/>
               <refstandard refid="w3c-rec-css3-color-20110607"/>
            </obgroup>
            <guide>Applications must support the following
browsers: Microsoft Internet Explorer v9.0 and
newer, and Mozilla Firefox 16.0 and newer.
When a supported browser is not true to the
standard, choose to support the browser that is
closest to the standard.</guide>
            <guide>Some organizations or end user devices do not
allow the use of proprietary extensions such as
Microsoft Web Parts, Microsoft Silverlight or
Adobe Flash. Those technologies shall be
avoided. Implementers shall use open standard
based solutions (HTML5 / CSS3) instead.</guide>
         </serviceprofile>
         <serviceprofile title="Geospatial Web Feeds Profile">
            <description>The Geospatial Web Feeds Profile provides standards and guidance for the delivery of geospatial content to web sites and to user agents, including the encoding of location as part of web feeds. Feed processing software is required to either read or ignore these extensions and shall not fail if these extensions are present, so there is no danger of breaking someone's feed reader (or publisher) by including this element in a feed.</description>
            <reftaxonomy refid="ts-ces-soa-web-host"/>
            <obgroup obligation="required">
               <refstandard refid="ogc-06-050r3"/>
            </obgroup>
            <obgroup obligation="mandatory">
               <refstandard refid="ogc-11-044"/>
            </obgroup>
         </serviceprofile>
         <serviceprofile title="Web Services Profile">
            <description>The Web Services Profile provides standards and guidance for transport-neutral mechanisms to address structured exchange of information in a decentralized, distributed environment via web services.</description>
            <reftaxonomy refid="ts-ces-soa-web-host"/>
            <obgroup obligation="mandatory">
               <refstandard refid="w3c-rec-soap11"/>
               <refstandard refid="w3c-note-wsdl-20010315"/>
               <refstandard refid="w3c-note-wsdl20-soap11-binding-20070626"/>
               <refstandard refid="w3c-address"/>
            </obgroup>
            <obgroup obligation="conditional">
               <refstandard refid="acm-2002-rest-toit"/>
            </obgroup>
            <obgroup obligation="mandatory">