=== AndreaGriffiths11/nisp-tools/src/schema/dtd/documents.dtd
<!-- ...................................................................... -->
<!-- Documents XML DTD V1.1 ............................................... -->
<!-- File documents.dtd ................................................... -->

<!-- Copyright 2003-2009 Danish Defence Research Establishment and
     NATO Command, Control and Consultation Organisation (NC3O).

     Permission to use, copy, modify and distribute the Standards XML
     DTD and its accompanying documentation for any purpose and
     without fee is hereby granted in perpetuity, provided that the
     above copyright notice and this paragraph appear in all copies.
     The copyright holders make no representation about the
     suitability of the DTD for any purpose.  It is provided "as is"
     without expressed or implied warranty.

     If you modify the Documents XML DTD in any way, except for
     declaring and referencing additional sets of general entities and
     declaring additional notations, label your DTD as a variant of
     Documents DTD. -->

<!-- ...................................................................... -->

<!-- This is the driver file for V1.1 of the Documents DTD.
     Please use the following formal public identifier to identify it:

     "-//DDRE//DTD Documents XML V1.1//EN"

     Example, use the FPI in the DOCTYPE declaration:

     <!DOCTYPE documents PUBLIC "-//DDRE//DTD Documents XML V1.1//EN"
                                "documents.dtd"
               [...]>

     Or, if you have a higher-level driver file that customizes Documentss,
     use the FPI in the parameter entity declaration:

     <!ENTITY % DocumentsDTD PUBLIC "-//DDRE//DTD Documents XML V1.1//EN"
                "documents.dtd">
     %DocumentsDTD;

-->



<!ELEMENT documents (versioninfo, directory*)>

<!ELEMENT versioninfo (package, release, ihb)>

<!ELEMENT package EMPTY>

<!ATTLIST package 
          major CDATA #REQUIRED
          minor CDATA #REQUIRED>

<!ELEMENT release EMPTY>

<!ATTLIST release date CDATA #REQUIRED>

<!ELEMENT ihb EMPTY>

<!ATTLIST ihb 
          major CDATA #REQUIRED
          minor CDATA #REQUIRED>

<!ELEMENT directory (docinfo)>

<!ATTLIST directory dir CDATA #REQUIRED>

<!ELEMENT docinfo (main, parts*, figures*, titles, resolve, targets)>

<!ATTLIST docinfo 
          id ID #REQUIRED>

<!ELEMENT main (#PCDATA)>

<!ELEMENT parts (part+)>

<!ELEMENT part (#PCDATA)>

<!ELEMENT figures EMPTY>

<!ELEMENT titles (short, title, longtitle)>

<!ELEMENT short (#PCDATA)>

<!ELEMENT title (#PCDATA)>

<!ELEMENT longtitle (#PCDATA)>

<!ELEMENT resolve (#PCDATA)>

<!ATTLIST resolve
          usedb (yes|no) "no"
          db CDATA #IMPLIED>

<!ELEMENT targets (target+)>

<!ELEMENT target (#PCDATA)>

<!ATTLIST target 
          type CDATA #REQUIRED
          embedsvg (yes|no) "no"
          heapmemory CDATA #IMPLIED
          stackmemory CDATA #IMPLIED>

=== AndreaGriffiths11/nisp-tools/src/documents.xml
<?xml version="1.0"?>

<!DOCTYPE documents PUBLIC "-//DDRE//DTD Documents XML V1.0//EN"
                           "schema/dtd/documents.dtd" [

<!ENTITY % src-info SYSTEM "VERSION">
%src-info;

]>

<documents>
  <versioninfo>
    <package major="&src-version-major;" minor="&src-version-minor;"/>
    <release date="&src-release-date;"/>
  </versioninfo>

  <directory dir="volume1">
    <docinfo id="vol1">
      <main>vol1.xml</main>
      <figures/>
      <titles>
        <short>V1</short>
        <title>Volume 1</title>
        <menutitle>Introduction</menutitle>
        <longtitle>Introduction and Management</longtitle>
      </titles>

      <resolve>resolve.xsl</resolve>

      <targets>
        <target type="html">index.html</target>
        <target type="pdf">NISP-Vol1</target>
      </targets>
    </docinfo>
  </directory>

  <directory dir="volume2">
    <docinfo id="vol2">
      <main>vol2.xml</main>
      <figures/>
      <titles>
        <short>V2</short>
        <title>Volume 2</title>
        <menutitle>Standards</menutitle>
        <longtitle>Agreed Interoperability Standards and Profiles</longtitle>
      </titles>

      <resolve usedb="yes" db="standards.xml">resolve-nodes.xsl</resolve>

      <targets>
        <target type="html">index.html</target>
        <target type="pdf">NISP-Vol2</target>
      </targets>
    </docinfo>
  </directory>


  <directory dir="volume3">
    <docinfo id="vol3">
      <main>vol3.xml</main>
      <figures/>
      <titles>
        <short>V3</short>
        <title>Volume 3</title>
        <menutitle>Profiles</menutitle>
        <longtitle>Candidate Standards and Profiles</longtitle>
      </titles>

      <resolve usedb="yes" db="standards.xml">resolve-nodes.xsl</resolve>

      <targets>
        <target type="html">index.html</target>
        <target type="pdf">NISP-Vol3</target>
      </targets>
    </docinfo>
  </directory>

</documents>
